name: Build and Deploy to S3

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust this to your desired Node version

    - name: Install dependencies
      run: npm install

    - name: Create deployment artifact
      run: zip -r node-app.zip .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust this to your AWS region

    - name: Upload to S3
      run: aws s3 cp node-app.zip s3://${{ secrets.AWS_S3_BUCKET }}/node-app.zip
