name: Deploy app to ASG

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust this to your AWS region

    - name: Upload to S3
      run: |
        aws deploy create-deployment \
          --application-name my-codedeploy-app \
          --deployment-group-name my-deployment-group \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},bundleType=zip,key=node-app.zip
