name: Delete Terraform Workspace

on:
  push:
    branches:
      - master
  
jobs:
  delete-workspace:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Terraform CLI
      uses: hashicorp/setup-terraform@v1
      
    - name: Switch to a temporary workspace (optional)
      run: terraform workspace new temp-workspace
      
    - name: Select the workspace to delete
      run: terraform workspace select terraform-sandeep-aws
      
    - name: Delete the workspace
      run: terraform workspace delete terraform-sandeep-aws -force
      
    - name: Clean up
      run: terraform workspace select default && terraform workspace delete temp-workspace -force
